#!/usr/bin/env bash
set -euo pipefail
fail() { echo "FAIL: $1" >&2; exit 1; }
for file in hatnikotni-chat.php uninstall.php includes/*.php; do
  [ -f "$file" ] || fail "Missing expected PHP file: $file"
  php -l "$file" >/dev/null || fail "PHP syntax error: $file"
done
grep -q "Text Domain: hatnikotni-chat" hatnikotni-chat.php || fail "Text domain mismatch"
grep -q "Plugin URI: https://github.com/dejabey/hatnikotni-chat" hatnikotni-chat.php || fail "Public Plugin URI missing"
grep -q "HATNCH_VERSION" hatnikotni-chat.php || fail "Version constant missing"
grep -q "class-hatnch-privacy.php" hatnikotni-chat.php || fail "Privacy module load missing"
grep -q "hatnch_has_analytics_consent" includes/class-hatnch-privacy.php || fail "Analytics consent filter missing"
grep -q "hatnch_analytics_consent" includes/class-hatnch-privacy.php || fail "Native consent cookie missing"
grep -q "wp_add_privacy_policy_content" includes/class-hatnch-privacy.php || fail "Privacy policy integration missing"
grep -q "hatnch-privacy-toggle" includes/class-hatnch-whatsapp.php || fail "Privacy choices control missing"
grep -q "hatnch-privacy-consent-input" includes/class-hatnch-whatsapp.php || fail "Analytics consent switch missing"
grep -q "role=\"switch\"" includes/class-hatnch-whatsapp.php || fail "Accessible switch role missing"
grep -q "'Details'" includes/class-hatnch-whatsapp.php || fail "English source label missing"
grep -q "'Privacy'" includes/class-hatnch-whatsapp.php || fail "English source privacy label missing"
grep -Fq "__( 'Contact Us', 'hatnikotni-chat' )" includes/class-hatnch-whatsapp.php || fail "Default button label must follow WordPress locale"
grep -q "'Reject'" includes/class-hatnch-whatsapp.php || fail "English source reject label missing"
grep -q "'Accept'" includes/class-hatnch-whatsapp.php || fail "English source accept label missing"
grep -q "get_privacy_policy_url" includes/class-hatnch-whatsapp.php || fail "Privacy policy link missing"
grep -q "hatnikotni-chat-privacy.js" includes/class-hatnch-whatsapp.php || fail "Privacy script enqueue missing"
grep -q "writeConsent('yes')" assets/js/hatnikotni-chat-privacy.js || fail "Explicit consent write missing"
grep -q "writeConsent('no')" assets/js/hatnikotni-chat-privacy.js || fail "Consent rejection write missing"
grep -q "readConsent()" assets/js/hatnikotni-chat-privacy.js || fail "Saved consent initialization missing"
grep -q "clearCampaignCookie()" assets/js/hatnikotni-chat-privacy.js || fail "Campaign cookie clearing function missing"
grep -q "\$wpdb->prefix . 'hatnch_contacts'" includes/class-hatnch-contacts.php || fail "Contacts table prefix contract missing"
grep -q "\$wpdb->prefix . 'hatnch_events'" includes/class-hatnch-analytics.php || fail "Events table prefix contract missing"
grep -q "get_charset_collate" includes/class-hatnch-contacts.php || fail "Contacts charset contract missing"
grep -q "get_charset_collate" includes/class-hatnch-analytics.php || fail "Events charset contract missing"
grep -q "dbDelta" includes/class-hatnch-contacts.php || fail "Contacts dbDelta contract missing"
grep -q "dbDelta" includes/class-hatnch-analytics.php || fail "Events dbDelta contract missing"
grep -q "WP_UNINSTALL_PLUGIN" uninstall.php || fail "Uninstall guard missing"
grep -q "hatnch_routing_state" uninstall.php || fail "Routing state uninstall cleanup missing"
grep -q "function save" includes/class-hatnch-contacts.php || fail "Contact save contract missing"
grep -q "function set_status" includes/class-hatnch-contacts.php || fail "Contact status contract missing"
grep -q "admin_post_hatnch_save_contact" includes/class-hatnch-admin.php || fail "Contact save admin action missing"
grep -q "check_admin_referer" includes/class-hatnch-admin.php || fail "Admin nonce contract missing"
grep -q "current_user_can( 'manage_options' )" includes/class-hatnch-admin.php || fail "Admin capability contract missing"
grep -q "wp_safe_redirect" includes/class-hatnch-admin.php || fail "Safe redirect contract missing"
grep -q "maybe_upgrade" includes/class-hatnch-plugin.php || fail "Database upgrade contract missing"
grep -q "hatnch_save_settings" includes/class-hatnch-admin.php || fail "Settings save action missing"
grep -q "routing_method" includes/class-hatnch-admin.php || fail "Routing settings contract missing"
grep -q "case 'direct'" includes/class-hatnch-routing.php || fail "Direct routing contract missing"
grep -q "case 'random'" includes/class-hatnch-routing.php || fail "Random routing contract missing"
grep -q "case 'round_robin'" includes/class-hatnch-routing.php || fail "Round-robin routing contract missing"
grep -q "get_active" includes/class-hatnch-routing.php || fail "Active-contact routing contract missing"
grep -q "hatnch_routing_state" includes/class-hatnch-routing.php || fail "Round-robin state contract missing"
grep -q "admin_post_nopriv_hatnch_whatsapp_click" includes/class-hatnch-whatsapp.php || fail "Public WhatsApp action contract missing"
grep -q "HATNCH_Analytics::record_click" includes/class-hatnch-whatsapp.php || fail "Correct analytics handler call missing"
if grep -q "HATNCH_Analitik::record_click" includes/class-hatnch-whatsapp.php; then fail "Misspelled analytics handler call must not exist"; fi
grep -q "https://wa.me/" includes/class-hatnch-whatsapp.php || fail "WhatsApp URL contract missing"
grep -q "setcookie" includes/class-hatnch-campaign.php || fail "Campaign cookie contract missing"
grep -q "hatnch_campaign" includes/class-hatnch-campaign.php || fail "Campaign cookie name contract missing"
grep -q "has_analytics_consent" includes/class-hatnch-campaign.php || fail "Campaign consent gate missing"
grep -q "has_analytics_consent" includes/class-hatnch-analytics.php || fail "Analytics consent gate missing"
grep -q "whatsapp_click" includes/class-hatnch-analytics.php || fail "Analytics event contract missing"
grep -q "get_summary" includes/class-hatnch-analytics.php || fail "Analytics summary contract missing"
grep -q "function cleanup" includes/class-hatnch-analytics.php || fail "Analytics cleanup contract missing"
grep -q "hatnch_daily_cleanup" includes/class-hatnch-plugin.php || fail "Analytics cleanup schedule contract missing"
grep -q "hatnch-analytics" includes/class-hatnch-analytics-admin.php || fail "Analytics admin contract missing"
grep -q "hatnch-inline" includes/class-hatnch-shortcode.php || fail "Shortcode rendering contract missing"
if grep -R -q "WhatsApp Kami\|Baca lagi\|Dasar Privasi" includes assets/js; then fail "Malay UI strings must come from translation files, not source code"; fi
grep -q "=== Hatnikotni Chat ===" readme.txt || fail "WordPress.org readme missing"
grep -q "Stable tag:" readme.txt || fail "WordPress.org stable tag missing"

grep -q "hatnch_load_textdomain" hatnikotni-chat.php || fail "Plugin textdomain loader missing"
grep -q "add_action( 'init', 'hatnch_load_textdomain' )" hatnikotni-chat.php || fail "Text domain must load on init"
grep -q "Analytics accepted." includes/class-hatnch-whatsapp.php || fail "English source consent message missing"
grep -q "Analytics rejected. WhatsApp remains available." includes/class-hatnch-whatsapp.php || fail "English source rejection message missing"
grep -q "consentAccepted" includes/class-hatnch-whatsapp.php || fail "Localized JavaScript consent strings missing"
grep -q "consentRejected" includes/class-hatnch-whatsapp.php || fail "Localized JavaScript rejection string missing"
test -f languages/hatnikotni-chat.pot || fail "Translation template missing"
test -f languages/hatnikotni-chat-ms_MY.po || fail "Malay translation source missing"
echo "PASS: Hatnikotni Chat contracts"
